version: "3.8"

services:
  triton:
    image: nvcr.io/nvidia/tritonserver:25.06-py3
    container_name: triton-server
    ports:
      - "8000:8000"  # gRPC
      - "8001:8001"  # HTTP
      - "8002:8002"  # Metrics
    volumes:
      - ./models:/models
    command: >
      tritonserver --model-repository=/models

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
